version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
      - ./public:/usr/share/nginx/html  
    depends_on:
      - websocket 
    networks:
      - app-network

  websocket:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
